version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/app
      - dbdata:/usr/src/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    command: "npm run dev"
    ports:
      - "8080:8080"

volumes:
  dbdata: